### ISSUE TITLE
Remove chart border

### ISSUE THREAD

**Issue by junste** [knowm/XChart#408] opened 2020-01-17 15:35 UTC
Hi,

Is there a way to get rid of the border around the chart? I would like to have the title on top but no border at all around the chart.

Please see attached image.

Regards,
Stefan Junsved

<img width="544" alt="example" src="https://user-images.githubusercontent.com/1788911/72624438-43223d00-3947-11ea-9f58-625d99a61967.png">

**Comment by Mr14huashao** [comment] 2020-01-19 02:11
@junste 

Set `plotBorderColor` and `legendBorderColor` as `chartBackgroundColor`.
```java
chart.getStyler().setChartBackgroundColor(Color.WHITE);
chart.getStyler().setLegendBorderColor(Color.WHITE);
chart.getStyler().setPlotBorderColor(Color.WHITE);
```
The effect is as follows:
![4](https://user-images.githubusercontent.com/57353473/72673291-2864db00-3aa3-11ea-9d48-8cdfb99a1478.png)

**Comment by junste** [comment] 2020-01-19 07:57
Thank you so much!

Regards,
Stefan

**Comment by Mr14huashao** [comment] 2020-01-19 08:06
@junste 
If the issue is resolved, you can help close this issue.

**Closed** 2020-01-19 08:12 UTC
