### ISSUE TITLE
tooltip and cursor display bug with real time xy chart

### ISSUE THREAD

**Issue by landret** [knowm/XChart#553] opened 2021-01-30 00:50 UTC
Hi,
there are 2 bugs with the tooltip display with real time xy chart (settings used: tooltip enabled, tooltip not always displayed):
- if we put the mouse on a point, the tooltip appears. However, as long as we don't move the mouse, it will still appear at the same position and with the same value even for the next frames after xychart updates
- after few seconds, the tooltip will start to appear for a point quite far at its right. This bug is new and was not occuring in version 3.6.4

![tooltip bug](https://user-images.githubusercontent.com/19358486/106341397-38c89d80-6241-11eb-810b-afc96ec85d70.png)

These bugs also affect the cursor (at least bug 1)
![cursor](https://user-images.githubusercontent.com/19358486/106373720-7d773600-6320-11eb-8607-32ba331c546b.png)

**Comment by ramonchiara** [comment] 2021-06-01 17:02
I'm having same issue.
I guess that the problem is: when `XYSeries.replaceData(double[] newXData, double[] newYData, double[] newExtraValues)`, is used, the list of tooltips aren't being cleared.

**Comment by landret** [comment] 2021-07-07 22:03
If @ramonchiara solution works, could a pull request be created to solve these issues?

**Comment by timmolter** [comment] 2021-08-09 10:11
fixed with merge

**Closed by timmolter** 2021-08-09 10:11 UTC
